[project]
site_name = "Lerax"
site_url = "https://lerax.tedpinkerton.ca/"
repo_url = "https://github.com/RunnersNum40/lerax"
repo_name = "RunnersNum40/lerax"
site_description = "Lerax Library Documentation"
site_author = "Theodore Pinkerton"
copyright = "&copy; 2025 Theodore Pinkerton"
extra_css = ["stylesheets/extra.css"]

[project.extra.status]
draft = "Draft"

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.code.annotate",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/book-x"
repo = "fontawesome/brands/github"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src", "examples"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_symbol_type_toc = true
show_symbol_type_heading = true
show_source = false
separate_signature = true
members_order = "source"
show_signature_annotations = true
show_signature_type_parameters = true
show_root_heading = true
show_root_full_path = true
type_parameter_headings = true
annotations_path = "source"

[project.markdown_extensions.attr_list]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.admonition]
