[project]
site_name = "Lerax"
site_url = "https://lerax.tedpinkerton.ca/"
repo_url = "https://github.com/RunnersNum40/lerax"
repo_name = "RunnersNum40/lerax"
site_description = "Lerax Library Documentation"
site_author = "Theodore Pinkerton"
copyright = "&copy; 2025 Theodore Pinkerton"
extra_css = ["stylesheets/extra.css"]

[project.extra.status]
draft = "Draft"

[project.theme]
# favicon =
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.code.annotate",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  "navigation.sections",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
  "toc.integrate",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/book-x"
repo = "fontawesome/brands/github"

[project.markdown_extensions.attr_list]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.footnotes]
